In [1]:
import numpy as np

In [2]:
"Basics of numpy"

'Basics of numpy'

In [3]:
arr = np.array([1, 2, 3, 4.0])
arr

array([1., 2., 3., 4.])

In [4]:
type(arr) #object type in ndarray not array

numpy.ndarray

In [5]:
arr.dtype # np.array extends types if many

dtype('float64')

In [6]:
isinstance(arr[0], int) #int32 is not integer!

False

In [7]:
arr = np.array([1, 2, 3, False, 4.5, 'hello_world'], dtype='U32') #bool is numeric, U32 is similar to base object
arr

array(['1', '2', '3', 'False', '4.5', 'hello_world'], dtype='<U32')

In [8]:
arr.dtype

dtype('<U32')

In [9]:
arr = np.array([1, 2, 3, False, 4.5, 'hello_world'], dtype=object) # establish dtype on data load to prevent errors on file loading
arr.dtype # object is last resource : )

dtype('O')

In [10]:
"Shapes and dimensions"

'Shapes and dimensions'

In [11]:
arr.shape # nests

(6,)

In [12]:
arr = np.array([[1, 2], [3, 4]]) # elements HAVE to be same lenght
arr.shape # axis, (zbior obserwacji, populacja obserwacji)

(2, 2)

In [13]:
arr

array([[1, 2],
       [3, 4]])

In [14]:
arr = np.arange(60).reshape(5, 12)
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [15]:
arr = np.arange(60).reshape(60, 1, 1, 1)
arr # os cech, os obserwacji

array([[[[ 0]]],


       [[[ 1]]],


       [[[ 2]]],


       [[[ 3]]],


       [[[ 4]]],


       [[[ 5]]],


       [[[ 6]]],


       [[[ 7]]],


       [[[ 8]]],


       [[[ 9]]],


       [[[10]]],


       [[[11]]],


       [[[12]]],


       [[[13]]],


       [[[14]]],


       [[[15]]],


       [[[16]]],


       [[[17]]],


       [[[18]]],


       [[[19]]],


       [[[20]]],


       [[[21]]],


       [[[22]]],


       [[[23]]],


       [[[24]]],


       [[[25]]],


       [[[26]]],


       [[[27]]],


       [[[28]]],


       [[[29]]],


       [[[30]]],


       [[[31]]],


       [[[32]]],


       [[[33]]],


       [[[34]]],


       [[[35]]],


       [[[36]]],


       [[[37]]],


       [[[38]]],


       [[[39]]],


       [[[40]]],


       [[[41]]],


       [[[42]]],


       [[[43]]],


       [[[44]]],


       [[[45]]],


       [[[46]]],


       [[[47]]],


       [[[48]]],


       [[[49]]],


       [[[50]]],


       [[[51]]],


       [[[52

In [16]:
arr = np.arange(60).reshape(1,1,1, 60)
arr # os cech, os obserwacji

array([[[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14,
          15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
          30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
          45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]]]])

In [17]:
arr = np.arange(60).reshape(3, 4, 5)
arr 

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [18]:
shape = 3, 480, 640, 4 # array like object, no need for a list or an array
N = np.product(shape)
arr = np.arange(N).reshape(shape)
arr # analysis on 2d is not possible, we can only use arr.shape in this case to understand it

array([[[[      0,       1,       2,       3],
         [      4,       5,       6,       7],
         [      8,       9,      10,      11],
         ...,
         [   2548,    2549,    2550,    2551],
         [   2552,    2553,    2554,    2555],
         [   2556,    2557,    2558,    2559]],

        [[   2560,    2561,    2562,    2563],
         [   2564,    2565,    2566,    2567],
         [   2568,    2569,    2570,    2571],
         ...,
         [   5108,    5109,    5110,    5111],
         [   5112,    5113,    5114,    5115],
         [   5116,    5117,    5118,    5119]],

        [[   5120,    5121,    5122,    5123],
         [   5124,    5125,    5126,    5127],
         [   5128,    5129,    5130,    5131],
         ...,
         [   7668,    7669,    7670,    7671],
         [   7672,    7673,    7674,    7675],
         [   7676,    7677,    7678,    7679]],

        ...,

        [[1221120, 1221121, 1221122, 1221123],
         [1221124, 1221125, 1221126, 1221127]

In [19]:
shape = 3, 2, 3, 4
N = np.product(shape)
arr = np.arange(N).reshape(shape)
arr

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]],


       [[[24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35]],

        [[36, 37, 38, 39],
         [40, 41, 42, 43],
         [44, 45, 46, 47]]],


       [[[48, 49, 50, 51],
         [52, 53, 54, 55],
         [56, 57, 58, 59]],

        [[60, 61, 62, 63],
         [64, 65, 66, 67],
         [68, 69, 70, 71]]]])

In [20]:
arr[-1]

array([[[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]],

       [[60, 61, 62, 63],
        [64, 65, 66, 67],
        [68, 69, 70, 71]]])

In [21]:
arr[0][1]

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [22]:
arr[0][1][2][3]

23

In [23]:
arr[0, 1, 2, 3]

23

In [24]:
arr.shape

(3, 2, 3, 4)

In [25]:
"More on indexing and slicing"

'More on indexing and slicing'

In [26]:
shape = 2, 3, 4
N = np.product(shape)
arr = np.arange(N).reshape(shape)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [27]:
arr[1,2]

array([20, 21, 22, 23])

In [45]:
arr[:, 0]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [29]:
arr[:, :,  0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [30]:
arr[..., 0]

array([[ 0,  4,  8],
       [12, 16, 20]])

In [31]:
arr[::, 0]

array([[ 0,  1,  2,  3],
       [12, 13, 14, 15]])

In [32]:
"Selection"

'Selection'

In [33]:
shape = 2, 3, 4
N = np.product(shape)
arr = np.arange(N).reshape(shape)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [34]:
arr[[1, 0]]

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [35]:
arr[(1, 0)]

array([12, 13, 14, 15])

In [37]:
"listy i tuple sa traktowane inaczej niz normalnie"

'listy i tuple sa traktowane inaczej niz normalnie'

In [38]:
arr[[1, 0, 1], [1, 0, 2], [1, 0, 3]]

array([17,  0, 23])

In [39]:
"""indeksowanie za pomoca list zaweza mozliwosci dalszego zagniezdzania"""

'indeksowanie za pomoca list zaweza mozliwosci dalszego zagniezdzania'

In [40]:
arr[[1, 0, 1], [1, 0, 2], [1, 0, 3]]

array([17,  0, 23])

In [41]:
"logic"

'logic'

In [42]:
arr = np.array([[1, 0, 1, 0], [1, 0, 2, 1], [1, 0, 3, 2]])

In [43]:
arr % 3 == 0

array([[False,  True, False,  True],
       [False,  True, False, False],
       [False,  True,  True, False]])

In [44]:
shape = 2, 3, 4
N = np.product(shape)
arr = np.arange(N).reshape(shape)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [45]:
np.nonzero(arr % 3 == 0)

(array([0, 0, 0, 0, 1, 1, 1, 1], dtype=int64),
 array([0, 0, 1, 2, 0, 0, 1, 2], dtype=int64),
 array([0, 3, 2, 1, 0, 3, 2, 1], dtype=int64))

In [46]:
arr[np.nonzero(arr % 3 ==0)]

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [47]:
arr[np.nonzero(arr % 3 ==0)] = -1

In [48]:
arr

array([[[-1,  1,  2, -1],
        [ 4,  5, -1,  7],
        [ 8, -1, 10, 11]],

       [[-1, 13, 14, -1],
        [16, 17, -1, 19],
        [20, -1, 22, 23]]])

In [49]:
arr == -1

array([[[ True, False, False,  True],
        [False, False,  True, False],
        [False,  True, False, False]],

       [[ True, False, False,  True],
        [False, False,  True, False],
        [False,  True, False, False]]])

In [50]:
shape = 2, 3, 4
N = np.product(shape)
arr = np.arange(N).reshape(shape)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [51]:
arr[arr % 3 == 0] # same effect as with nonzero

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [52]:
arr[:, :, [True, False, True, False]]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [53]:
arr[:,:,[0,2]]

array([[[ 0,  2],
        [ 4,  6],
        [ 8, 10]],

       [[12, 14],
        [16, 18],
        [20, 22]]])

In [ ]:
"tip: operacje wektorowe sa lepsze niz manualne (numpy)"

In [ ]:
import pandas as pd

In [ ]:
pd.Series

In [ ]:
pd.DataFrame

In [ ]:
pd.Series([1, 2, 3])

In [ ]:
pd.Series([1, 2, 3, 4.5])

In [ ]:
df = pd.DataFrame({'A': [1,2,3], 'B': [4,5,6]})

In [ ]:
pd.DataFrame([[1,2,3], [4,5,6]])

In [ ]:
df.loc[1, :] #traktujemy jako tablice 2-wymiarowa

In [ ]:
df.loc[[True, False, True], :]

In [ ]:
df.loc[df['A'] > 1, :]


In [ ]:
# datasety, importy, merge -> pandas -> poniewaz jest to ustalane na zgodnosci indeksow